#! /bin/sh

#####################################################################
#
# Zhu Mingjun(zhumj1991@163.com)
# Feb. 23, 2017
#
#####################################################################
echo_separator()
{
	echo "#"
	echo "# $1"
	echo "#"
}

generate_mainmenu()
{
declare -a CPU_ARCH=(`find -L arch -maxdepth 1 -mindepth 1 -type d -print |\
					sed -e 's?^arch/??' -e 's?/[^/]*$??' -e 's?/? ?g' | \
					sort`)

declare -a KERNEL=(`find -L kernel -maxdepth 1 -mindepth 1 -type d -print |\
					sed -e 's?^kernel/??' -e 's?/[^/]*$??' -e 's?/? ?g' | \
					sort`)

declare -a PACKAGE=()

echo "#"
echo "# Automatically generated by 'make config'. don't edit."
echo "# Zhu Mingjun(zhumj1991@163.com)"
echo "#"
echo

echo "mainmenu \"RTOS Configuration\""
echo

#####################################################################
echo_separator "Select cpu"

echo "choice"
echo "	prompt \"Select architecture\""
echo "	default ARM"
echo

for ((i = 0; i < ${#CPU_ARCH[*]}; i++))
do
	CFG=$(echo ${CPU_ARCH[$i]} | tr '[:lower:]' '[:upper:]')
	DEF=${CFG}
	echo "config ${CFG}"
	echo "	bool \"${DEF} architecture\""
	echo
done

echo "endchoice"
echo

for ((i = 0; i < ${#CPU_ARCH[*]}; i++))
do
	if [ -f "arch/${CPU_ARCH[$i]}/Kconfig" ]; then
		echo "source \"arch/${CPU_ARCH[$i]}/Kconfig\""
	fi
done
echo

######################################################################
echo_separator "General setup"
echo "source \"scripts/Kconfig.rtos\""
echo

######################################################################
echo_separator "Select rtos kernel"

echo "menu \"Kernel configuration\""
echo

echo "choice"
echo "	prompt \"RTOS kernel\""
echo "	default RTOS_RTX"
echo

for ((i = 0; i < ${#KERNEL[*]}; i++))
do
	CFG="RTOS_"$(echo ${KERNEL[$i]} | tr '[:lower:]' '[:upper:]')
	echo "config ${CFG}"
	echo "	bool \"${KERNEL[$i]}\""
	echo
done

echo "endchoice"
echo


echo "config RTOS_KERNEL"
echo "	string"

for ((i = 0; i < ${#KERNEL[*]}; i++))
do
	CFG="RTOS_"$(echo ${KERNEL[$i]} | tr '[:lower:]' '[:upper:]')
	echo "	default \"${KERNEL[i]}\" if ${CFG}"
done
echo


for ((i = 0; i < ${#KERNEL[*]}; i++))
do
	if [ -f "kernel/${KERNEL[$i]}/Kconfig" ]; then
		echo "source \"kernel/${KERNEL[$i]}/Kconfig\""
	fi
done
echo

echo "endmenu"
echo

######################################################################
echo_separator "Select driver"
echo "menu \"Driver\""

echo "endmenu"
echo

######################################################################
echo_separator "Select package"
echo "menu \"Package\""

echo "endmenu"
echo

######################################################################
echo_separator "Select application"
echo "source \"app/Kconfig\""
echo
}

generate_mainmenu
